from datetime import datetime
VENUES = [
    {
        "id": 1,
        "name": "The Musical Hop",
        "genres": [1, 2, 3, 4, 5],
        "address": "1015 Folsom Street",
        "city": "San Francisco",
        "state": "CA",
        "phone": "123-123-1234",
        "website": "https://www.themusicalhop.com",
        "facebook_link": "https://www.facebook.com/TheMusicalHop",
        "seeking_talent": True,
        "seeking_description": "We are on the lookout for a local artist to play every two weeks. Please call us.",
        "image_link": "https://images.unsplash.com/photo-1543900694-133f37abaaa5?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=400&q=60",
    },
    {
        "id": 2,
        "name": "The Dueling Pianos Bar",
        "genres": [4, 6, 7],
        "address": "335 Delancey Street",
        "city": "New York",
        "state": "NY",
        "phone": "914-003-1132",
        "website": "https://www.theduelingpianos.com",
        "facebook_link": "https://www.facebook.com/theduelingpianos",
        "seeking_talent": False,
        "image_link": "https://images.unsplash.com/photo-1497032205916-ac775f0649ae?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=750&q=80",
    },
    {
        "id": 3,
        "name": "Park Square Live Music & Coffee",
        "genres": [8, 1, 4, 5],
        "address": "34 Whiskey Moore Ave",
        "city": "San Francisco",
        "state": "CA",
        "phone": "415-000-1234",
        "website": "https://www.parksquarelivemusicandcoffee.com",
        "facebook_link": "https://www.facebook.com/ParkSquareLiveMusicAndCoffee",
        "seeking_talent": False,
        "image_link": "https://images.unsplash.com/photo-1485686531765-ba63b07845a7?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=747&q=80",
        },
]

ARTISTS = [
    {
        "id": 1,
        "name": "Guns N Petals",
        "genres": [8],
        "city": "San Francisco",
        "state": "CA",
        "phone": "326-123-5000",
        "website": "https://www.gunsnpetalsband.com",
        "facebook_link": "https://www.facebook.com/GunsNPetals",
        "seeking_venue": True,
        "seeking_description": "Looking for shows to perform at in the San Francisco Bay Area!",
        "image_link": "https://images.unsplash.com/photo-1549213783-8284d0336c4f?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=300&q=80",
    },
    {
        "id": 2,
        "name": "Matt Quevedo",
        "genres": [1],
        "city": "New York",
        "state": "NY",
        "phone": "300-400-5000",
        "facebook_link": "https://www.facebook.com/mattquevedo923251523",
        "seeking_venue": False,
        "image_link": "https://images.unsplash.com/photo-1495223153807-b916f75de8c5?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=334&q=80",
    },
    {
        "id": 3,
        "name": "The Wild Sax Band",
        "genres": [1, 4],
        "city": "San Francisco",
        "state": "CA",
        "phone": "432-325-5432",
        "seeking_venue": False,
        "image_link": "https://images.unsplash.com/photo-1558369981-f9ca78462e61?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=794&q=80",
    },
]


SHOWS = [
    {
        "id": 1,
        "venue_id": 1,
        "artist_id": 1,
        "start_time": datetime(2019, 5, 21, 21, 30),
    },
    {
        "id": 2,
        "venue_id": 3,
        "artist_id": 2,
        "start_time": datetime(2019, 6, 15, 23, 0),
    },
    {
        "id": 3,
        "venue_id": 3,
        "artist_id": 3,
        "start_time": datetime(2035, 4, 1, 20, 0),
    },
    {
        "id": 4,
        "venue_id": 3,
        "artist_id": 3,
        "start_time": datetime(2035, 4, 8, 20, 0),
    },
    {
        "id": 5,
        "venue_id": 3,
        "artist_id": 3,
        "start_time": datetime(2035, 4, 15, 20, 0),
    },
]

GENRES = [
    {"id": 1, "name": "Jazz"},
    {"id": 2, "name": "Reggae"},
    {"id": 3, "name": "Swing"},
    {"id": 4, "name": "Classical"},
    {"id": 5, "name": "Folk"},
    {"id": 6, "name": "R&B"},
    {"id": 7, "name": "Hip-Hop"},
    {"id": 8, "name": "Rock n Roll"},
    {"id": 9, "name": "Alternative"},
    {"id": 10, "name": "Blues"},
    {"id": 11, "name": "Country"},
    {"id": 12, "name": "Electronic"},
    {"id": 13, "name": "Funk"},
    {"id": 14, "name": "Heavy Metal"},
    {"id": 15, "name": "Instrumental"},
    {"id": 16, "name": "Musical Theatre"},
    {"id": 17, "name": "Pop"},
    {"id": 18, "name": "Punk"},
    {"id": 19, "name": "Soul"},
    {"id": 20, "name": "Other"},
]
