"""Add constrains for duplicate shows

Revision ID: 09382fe07231
Revises: 96c07be93b76
Create Date: 2026-09-11 13:27:30.535244

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '09382fe07231'
down_revision = '96c07be93b76'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('show', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_show_artist_venue_start_time', ['artist_id', 'venue_id', 'start_time'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('show', schema=None) as batch_op:
        batch_op.drop_constraint('uq_show_artist_venue_start_time', type_='unique')

    # ### end Alembic commands ###
