"""change website fileld

Revision ID: f7360f85a006
Revises: 09382fe07231
Create Date: 2026-09-14 10:27:13.718638

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f7360f85a006'
down_revision = '09382fe07231'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('artist', schema=None) as batch_op:
        batch_op.add_column(sa.Column('website_link', sa.String(length=500), nullable=True))
        batch_op.drop_constraint(batch_op.f('uq_artist_name_state_website'), type_='unique')
        batch_op.create_unique_constraint('uq_artist_name_state_website', ['name', 'state', 'website_link'])
        batch_op.drop_column('website')

    with op.batch_alter_table('venue', schema=None) as batch_op:
        batch_op.add_column(sa.Column('website_link', sa.String(length=500), nullable=True))
        batch_op.drop_column('website')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('venue', schema=None) as batch_op:
        batch_op.add_column(sa.Column('website', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
        batch_op.drop_column('website_link')

    with op.batch_alter_table('artist', schema=None) as batch_op:
        batch_op.add_column(sa.Column('website', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
        batch_op.drop_constraint('uq_artist_name_state_website', type_='unique')
        batch_op.create_unique_constraint(batch_op.f('uq_artist_name_state_website'), ['name', 'state', 'website'], postgresql_nulls_not_distinct=False)
        batch_op.drop_column('website_link')

    # ### end Alembic commands ###
